### ISSUE TITLE
match trigger word without requiring a space

### ISSUE THREAD

**Issue by Bonkeybee** [Myrroddin/price-answer#1]
Example:
?[ItemLink] (doesn't work)
? [ItemLink] (works)

Currently adding a space between the trigger and the item name or link is required. For item links this should not be required.

**Comment by Myrroddin** [comment]
I will look into that.

**Comment by Myrroddin** [comment]
After much testing, I could do what you ask, but it would be a breaking change.  It is a nice suggestion, but I won't implement your idea.
```
?[ItemLink] -- would work
? 3[ItemLink] -- would work
?3[ItemLink] -- does not work
? 3 [ItemLink] -- does not work
```
